// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_next_feed_to_fetch.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getNextFeedToFetch = `-- name: GetNextFeedToFetch :one
SELECT id, created_at, updated_at, user_id, feed_id FROM feed_follows
WHERE user_id = $1 
ORDER BY updated_at ASC NULLS FIRST
`

func (q *Queries) GetNextFeedToFetch(ctx context.Context, userID uuid.UUID) (FeedFollow, error) {
	row := q.db.QueryRowContext(ctx, getNextFeedToFetch, userID)
	var i FeedFollow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}
