// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mark_feed_fetched.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const markFeedFetched = `-- name: MarkFeedFetched :exec

UPDATE feeds_fetched
SET updated_at = CURRENT_TIMESTAMP, last_fetched_at =  CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
`

type MarkFeedFetchedParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) MarkFeedFetched(ctx context.Context, arg MarkFeedFetchedParams) error {
	_, err := q.db.ExecContext(ctx, markFeedFetched, arg.ID, arg.UserID)
	return err
}
