// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: purge_users.sql

package database

import (
	"context"
)

const purgeUsers = `-- name: PurgeUsers :exec
DELETE FROM users
`

func (q *Queries) PurgeUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, purgeUsers)
	return err
}
